# Generated by Django 4.0.1 on 2022-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country_code_from', models.CharField(max_length=20)),
                ('country_code_to', models.CharField(max_length=20)),
                ('capacity', models.FloatField()),
            ],
        ),
    ]
