# Generated by Django 4.0.1 on 2022-01-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transmission',
            constraint=models.UniqueConstraint(fields=('timestamp', 'country_code_from', 'country_code_to'), name='constraint_unique'),
        ),
    ]
